FROM gethue/hue:latest

USER root
RUN apt update
RUN apt upgrade -y
RUN /usr/share/hue/build/env/bin/pip install mysqlclient
RUN /usr/share/hue/build/env/bin/pip install pyhive
RUN /usr/share/hue/build/env/bin/pip install psycopg2-binary
RUN /usr/share/hue/build/env/bin/pip install mozilla_django_oidc
RUN /usr/share/hue/build/env/bin/pip install nose
# RUN /usr/share/hue/build/env/bin/pip install cx_Oracle
# RUN /usr/share/hue/build/env/bin/pip install PyAthena
# RUN /usr/share/hue/build/env/bin/pip install phoenixdb
# RUN /usr/share/hue/build/env/bin/pip install pydruid
# RUN /usr/share/hue/build/env/bin/pip install ksql
# RUN /usr/share/hue/build/env/bin/pip install pybigquery pyasn1==0.4.1
# RUN /usr/share/hue/build/env/bin/pip install sqlalchemy-teradata
# RUN /usr/share/hue/build/env/bin/pip install ibm_db_sa
# RUN /usr/share/hue/build/env/bin/pip install git+https://github.com/gethue/PyHive
# RUN /usr/share/hue/build/env/bin/pip install thrift_sasl
# RUN /usr/share/hue/build/env/bin/pip install pyodbc
# RUN /usr/share/hue/build/env/bin/pip install pymssql
# RUN /usr/share/hue/build/env/bin/pip install sqlalchemy-vertica-python
# RUN /usr/share/hue/build/env/bin/pip install sqlalchemy-hana
# RUN /usr/share/hue/build/env/bin/pip install sqlalchemy-solr
# RUN /usr/share/hue/build/env/bin/pip install kylinpy
# RUN /usr/share/hue/build/env/bin/pip install sqlalchemy-clickhouse
# RUN /usr/share/hue/build/env/bin/pip install pytz==2021.1
# RUN /usr/share/hue/build/env/bin/pip install elasticsearch-dbapi
# RUN /usr/share/hue/build/env/bin/pip install pinotdb
# RUN /usr/share/hue/build/env/bin/pip install snowflake-sqlalchemy
# RUN /usr/share/hue/build/env/bin/pip install gsheetsdb

# RUN touch /usr/share/hue/desktop/hue.db
# RUN chmod -R 777 /usr/share/hue
# RUN chmod -R 777 /usr/share/hue/*

EXPOSE 8888